import { LenguageSelector } from "../components";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Cubo from "../public/images/cubo.jpg";
import Image from "next/image";
import Link from "next/link";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["home"])),
    },
  };
}

export default function Home(props) {
  const { t } = useTranslation();

  return (
    <div className="container">
      <Head>
        <title>LOCAL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
        <div className="navbar">
          <h1 className="navbar__logo">@LOCAL</h1>
          <LenguageSelector />
        </div>

        <div className="hero">
          <h1>{props.locale}</h1>
          <Image src={Cubo} alt="logo" className="hero__image-logo" />
          <div className="hero__information">
            <h1>
              Hola soy <span>CUBO</span>
            </h1>
            <p>Frontend Developer</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a> UWU </a>
      </footer>
    </div>
  );
}
