import {
  BaseSection,
  ButtonGrid,
  Header,
  Hero,
  SectionExperience,
} from "@/components";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Head from "next/head";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}

export default function Home(props) {
  const { t } = useTranslation();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className="container">
          <Hero translate={t} />

          <BaseSection
            title={{ ft: "About", st: "Me" }}
            description="aboutme"
          />

          <BaseSection
            title={{ ft: "Tech", st: "Stack" }}
            description="devstack"
          >
            <ButtonGrid />
          </BaseSection>

          <SectionExperience />

          <div className="about-me">
            <div className="about-me__title">
              <h1>My</h1>
              <h1>Projects</h1>
            </div>

            <p>
              Hi 👋, My name is Martin and I am a Software Engineer 🧑🏽‍💻 with
              experience at companies like Facebook, Amazon, and Disney, as well
              as various open source projects. I am passionate about using my
              skills to build innovative and user-friendly applications that
              make a positive impact on peoples lives.
            </p>
          </div>

          <div className="about-me">
            <div className="about-me__title">
              <h1>My</h1>
              <h1>Projects</h1>
            </div>

            <p>
              Hi 👋, My name is Martin and I am a Software Engineer 🧑🏽‍💻 with
              experience at companies like Facebook, Amazon, and Disney, as well
              as various open source projects. I am passionate about using my
              skills to build innovative and user-friendly applications that
              make a positive impact on peoples lives.
            </p>
          </div>
        </div>
      </main>

      <footer>
        <a> UWU </a>
      </footer>
    </div>
  );
}
