import { ButtonGrid, MyExperience, Header } from "@/components";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTheme } from "next-themes";
import { useTranslation } from "next-i18next";
import classNames from "classnames";
import Cubo from "../../public/images/cubo.jpg";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["home"])),
    },
  };
}

export default function Home(props) {
  const { theme } = useTheme();
  const { t } = useTranslation("home");

  var btnClass = classNames({
    dark: theme === "dark",
  });

  console.log(theme);

  return (
    <div className={`${btnClass}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <div className="container">
          <div className="hero">
            <Image src={Cubo} alt="logo" className="hero__image-logo" />
            <div className="hero__information">
              <div>
                <h1>{t("welcome")}</h1>
                <h1>{t("myName")}</h1>
              </div>
              <p>Frontend Developer</p>
            </div>
          </div>

          <div className="about-me">
            <div className="about-me__title">
              <h1>About</h1>
              <h1>Me</h1>
            </div>
            <ButtonGrid />
            <p>
              Hi 👋, My name is Martin and I am a Software Engineer 🧑🏽‍💻 with
              experience at companies like Facebook, Amazon, and Disney, as well
              as various open source projects. I am passionate about using my
              skills to build innovative and user-friendly applications that
              make a positive impact on peoples lives.
            </p>
          </div>

          <div className="about-me">
            <div className="about-me__title">
              <h1>Tech</h1>
              <h1>Stack</h1>
            </div>

            <p>
              Hi 👋, My name is Martin and I am a Software Engineer 🧑🏽‍💻 with
              experience at companies like Facebook, Amazon, and Disney, as well
              as various open source projects. I am passionate about using my
              skills to build innovative and user-friendly applications that
              make a positive impact on peoples lives.
            </p>
          </div>
          <MyExperience />
          <div className="about-me">
            <div className="about-me__title">
              <h1>My</h1>
              <h1>Projects</h1>
            </div>

            <p>
              Hi 👋, My name is Martin and I am a Software Engineer 🧑🏽‍💻 with
              experience at companies like Facebook, Amazon, and Disney, as well
              as various open source projects. I am passionate about using my
              skills to build innovative and user-friendly applications that
              make a positive impact on peoples lives.
            </p>
          </div>
          <div className="about-me">
            <div className="about-me__title">
              <h1>My</h1>
              <h1>Projects</h1>
            </div>

            <p>
              Hi 👋, My name is Martin and I am a Software Engineer 🧑🏽‍💻 with
              experience at companies like Facebook, Amazon, and Disney, as well
              as various open source projects. I am passionate about using my
              skills to build innovative and user-friendly applications that
              make a positive impact on peoples lives.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a> UWU </a>
      </footer>
    </div>
  );
}
